name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Deploy to EC2 instance via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Check if the AWS folder exists
            if [ ! -d "/home/ec2-user/AWS" ]; then
              echo "Directory does not exist. Cloning repository..."
              cd /home/ec2-user
              git clone https://github.com/aashishmishra5131/AWS.git
              cd AWS
            else
              echo "Directory exists. Pulling latest changes..."
              cd /home/ec2-user/AWS
              git pull origin main
            fi

            # Install dependencies
            npm install

            # Build the TypeScript code
            npm run build


            # Restart the application
            # If using pm2 (recommended for Node.js apps):
            # pm2 restart your-app-name
            # Or if it's a simple restart:
            # npm run start
